### ISSUE TITLE
Support for CommonJS

### ISSUE THREAD

**Issue by ishuvalov** [dotlottie/player-component#310]
Hi,
Thank you for developing and maintaining this great player. Do you consider adding CJS support in your package? It would be highly appreciated by developers which still have to stick with earlier Node version.
Thanks 🙏

**Comment by theashraf** [comment]
Thank you, @ishuvalov. To ensure we're on the same page, could you please specify which package you're referring to when you mention adding CJS support? Are you referring to @dotlottie/react-player?

**Comment by ishuvalov** [comment]
Yes, exactly. I also believe it has ESM-only deps.

**Comment by theashraf** [comment]
@ishuvalov, I assume you're using a bundler to process JSX, so there shouldn't be any issues if you're using a bundler like Webpack or Rollup. These bundlers are capable of handling both ESM and CJS modules

If the issue you're facing is relatde to Node.js version constraints during installation, you can bypass that check by using the --ignore-engines argument with npm install. Simply run `npm install --ignore-engines @dotlottie/react-player`

**Comment by theashraf** [comment]
@ishuvalov I need your help with a concrete use case for CJS support. I'm assuming that your trying to run your React tests in jest which includes the DotLottieReact component. 

As far as i know Jest does support ESM (ECMAScript Modules) since version 29. But, if you are using an older jest version, you can mock the DotLottieReact Component. 

The provided React component is not isomorphic; it is browser-only. In cases where you want to run it in tests, you have two options:
 * you can provide a mock so it doesn't affect your test setup since it doesn't add value when running in a Node environment.
 * you can switch to a test runner that can operate in a real browser environment, such as Jasmine, Karma, Cypress, or Vitest. These can run your tests and the DotLottieReact component seamlessly in the browser without any issues with ESM-only support.
 
This is because the lottie-web renderer used in this package relies heavily on browser APIs to draw the animation on the canvas/viewport.

In cases where you want to run your animations on the Node, I'd suggest taking a look at [dotlottie-web](https://github.com/lottiefiles/dotlottie-web). It is isomorphic and capable of running Lottie/dotLottie animations both in the browser and in a Node environment. and we have a short blog post here demonstrating how you can use [dotlottie-web](https://github.com/lottiefiles/dotlottie-web) to run and encode the animation frames into GIFs on the server. You can read it here: https://lottiefiles.com/blog/working-with-lottie-animations/converting-dotlottie-animations-to-gifs-with-dotlottie-web-player/.

**Comment by ishuvalov** [comment]
I see now that all my problems stem from usage of older Node and Jest versions (it is quite hard to upgrade them at the moment). Thank you for all your help and detailed explanation! You can close the issue.
